### ISSUE TITLE
FHIR api $lookup concept in extension

### ISSUE THREAD

**Issue by ivelina-yordanova** [b2ihealthcare/snow-owl#426]
Hi,

I was testing the $lookup endpoint and wanted to search for a concept in a snomed extension(the UK one) thinking the format should be **[snomed-base-uri]/[extension-module-id]** and passing the code of the concept. However, this does not work, not out of the box with the current setup.

I had a quick look at the code and seems like the path is build mainly based on the version as branch of the main codesystem, could not find where the extension module is used besides being verified. 

Can you please provide any guidelines how is this supposed to work?

Thanks

**Comment by ivelina-yordanova** [comment]
Am I not asking the right question or on the right way?

**Comment by cmark** [comment]
Hi @ivelina-yordanova, 

This is a good question and yes, it's not covered in the FHIR API docs, because it is not supported yet.
The best would be to somehow map the SNOMED URI you have described to Snow Owl's internal CodeSystem representation in order to look up the code from the correct branch, but there were multiple issues with the approaches so far (because the FHIR API Spec does not allow the logical ID to be used in the `$lookup` operation).
It is on our radar and we will try our best to solve this issue for the upcoming 7.2.0 release (which is planned to be released on 22th Nov).

Let me know if you have any further questions.

Cheers,
Mark

**Comment by ivelina-yordanova** [comment]
Hey, thanks for getting back to me. If it's possible to add it that would be great!

Actually I do have a bit of a side question. I am trying to setup the project in Eclipse and following the instructions but no matter what I tried I keep getting some variation of `Missing Constraint: Require-Bundle: <bundle>". I used to develop an Eclipse based product few years back and thought something will come back to me and I'll think of a way to resolve it but.. no luck so far.

The initial error (right out of the box when I import the projects and set the target env) is this in the screenshot. Within the individual plugins those dependencies are resolved but in the run config it fails.


<img width="934" alt="Screenshot 2019-11-14 at 14 10 39" src="https://user-images.githubusercontent.com/56301327/68864665-6b907f80-06e9-11ea-9612-3b7d7e9efc28.png">

**Comment by cmark** [comment]
Hi @ivelina-yordanova,

Yeah, run configurations could get out of sync easily and it is very hard to keep them in sync with the actual code and dependencies. 
I'll synchronize them for you. Please try again when you see the related commit message here on this issue.

Cheers,
Mark

**Comment by ivelina-yordanova** [comment]
Amazing, that seems to work now, although the endpoints are not behaving as expected but it's starting! Thanks

**Comment by ivelina-yordanova** [comment]
Ok, running that config ( mentioned in the readme) I can see the bundles get resolved and can query stuff in the osgi console, but for the life of me couldn't get the endpoints to work, I can only get the elasticsearch one but nothing on 8080/snowowl/*

**Comment by cmark** [comment]
Hi @ivelina-yordanova,

Yes, that is a tricky one, unfortunately.
The underlying tooling does not play nicely and will not start the REST API bundles automatically sometimes. You need to start them manually when you see the `osgi>` console.
To do that follow these steps:
1. Run the `ss jetty` command to get back the ID of the `org.eclipse.jetty.osgi.boot` bundle
2. Start `org.eclipse.jetty.osgi.boot` with `start <JETTY_BOOT_ID>`
3. Run the `ss rest` command to get back the ID of the `com.b2international.snowowl.core.rest` bundle
4. Start `com.b2international.snowowl.core.rest` with `start <CORE_REST_ID>`

You should see a bunch of log messages form Jetty which indicates that it is initializing. After successful init you will be able to use the API at `http://localhost:8080/snowowl`.

Another thing to make sure it's available is the API website under the path `com.b2international.snowowl.core.rest/site`. If that folder is empty (even after a project refresh), then you need to manually trigger a Maven Project Update on that project with `Alt + F5`.
This downloads a `Node.js` instance and will build the API docs from `snow-owl-api-docs` folder.

Let me know if this works for you or have any further questions.

Regards,
Mark

**Comment by ivelina-yordanova** [comment]
🤦‍♀ I figured it would be something like that but for some reason I was trying to start the `om.b2international.snowowl.core.rest` without starting the other one first, didn't even noticed it wasn't running... Thanks again
Isn't this "just" a question of fixing the start level of these bundles? I the osgi boot is even one level after the default one? And making them autostart, tried it, think it works.

**Comment by cmark** [comment]
The order actually does not matter, because the `jetty.osgi.boot` bundle will deploy any bundle that is in starting state and it's a Web Application Bundle (WAB).
Yes, essentially the bundle start level should solve this, but in practice, this does not work as it is supposed to. Sometimes it starts the boot bundle too soon (before the core infrastructure) and the REST API init will fail because the core services are just not there yet. 
Good to know, once you have started the launch configuration correctly, it stores the bundle start order in your workspace configuration area and will use that the next time you start the config.

Anyway, feel free to experiment with it and please do share your findings with us. Thank you!

**Comment by ivelina-yordanova** [comment]
Hi @cmark 

I just came back to this and saw you have made some changes referring to the ticket, but cannot quite understand what's the status of it? 

Has this been enabled now or is work in progress?

Thanks,
Ivelina

**Comment by cmark** [comment]
Hi @ivelina-yordanova,

Sorry for my late reply.
This work has been delayed due to higher priority tasks for the release of Snow Owl 7.4.0, such as Elasticsearch 7.x support, performance improvements, stability. The 7.4.0 will be released on Monday, 24th of Feb here on GitHub. 
We will likely include the FHIR API URI/$lookup changes in the next 7.5.0 release.

Cheers,
Mark

**Comment by ivelina-yordanova** [comment]
Hi @cmark 

That sounds great, will look out for this one. 

Thanks

**Comment by cmark** [comment]
Hi @ivelina-yordanova,

Just a heads up, this feature could not make it into the 7.5.x releases. 
I'll let you know when we have the capacity to work on the issue and what will be the final release version that includes this feature.

Cheers,
Mark

**Comment by ivelina-yordanova** [comment]
Hi @cmark,

Thanks for the heads up, appreciate it.

We will probably proceed with what we already have for now.

Regards,
Ivelina

**Comment by cmark** [comment]
Hi @ivelina-yordanova,

Due to some recent improvements and reimplementation of Snow Owl's internals for the upcoming 8.0 release, we have been able to resolve this issue and provide the capability to properly `$lookup` a concept in extension.
Stay tuned for the 8.0 release announcement.

Cheers,
Mark

**Comment by cmark** [comment]
Hi @ivelina-yordanova,

The `$lookup` operation now properly recognizes extension SNOMED CT URIs with modules and dispatches requests to the correct content so extension concepts are finally coming back via FHIR API nicely regardless where are actually located in the branch system. See release [8.0.0](https://github.com/b2ihealthcare/snow-owl/releases/tag/v8.0.0) for details.

Cheers,
Mark
