### ISSUE TITLE
History of a concept

### ISSUE THREAD

**Issue by joshlk** [b2ihealthcare/snow-owl#433]
Hi,

I would like to be able to view the historical changes to a concept. For example, on date X relationship Y was added. I can't seem to find a feature that provides that functionality. Is it possible to view a concept at a given commit? Also is it possible to be able to see the changes that were made with a commit?

A commit could be a SNOMED delta update or changes done via snow owl.

Thanks,
Josh

**Comment by cmark** [comment]
Hi @joshlk,

Thank you for your questions.

> I would like to be able to view the historical changes to a concept. For example, on date X relationship Y was added. I can't seem to find a feature that provides that functionality.

> Also is it possible to be able to see the changes that were made with a commit?
These two are possible by using the Commit API in the SNOMED CT REST API:
See these endpoints:

`GET http://localhost:8080/snowowl/snomed-ct/v3/commits`
 - Returns all commits (by default the first 50)
 - Filter them by properties such as `branch`, `timestamp`, etc.
 - You can filter them by `affectedComponentId` (which can be the concept or an ID of any other component that can change)
 - You can also sort the commits by timestamp (by default it is sorted by `timestamp` descending order)
 - And page them using `searchAfter`

`GET http://localhost:8080/snowowl/snomed-ct/v3/commits/{commitId}`
 - Returns a specific commit by ID

A Commit model has properties like `author`, `message` and the usual info but also the `details` list.
A `CommitDetail` represents a single change made by the commit. For example, when a `moduleId` changes on a concept, it will be represented as a `CommitDetail`. By default this information is not returned because it can become really huge, especially if you think about SNOMED CT releases.
To get them back, filter the API by a given concept ID and expand the `details()` object, using the special expand syntax in the `expand` query parameter.

For example, to get back the history of SNOMED CT's `404684003|Clinical Finding|`, you can execute this request:
```
curl http://localhost:8080/snowowl/snomed-ct/v3/commits?affectedComponentId=404684003&expand=details()
```

>  Is it possible to view a concept at a given commit?

To view a component (not just a concept) at a given commit, you can use the branch path expressions feature (not documented yet):
The following branchPath expressions are supported:
- `<branch>@<timestamp>` - Query the branch at the given timestamp (provided in milliseconds since epoch). NOTE: the `@` character must be URL escaped to `%40`. This feature is work in progress and the syntax might change in the future to incorporate some URL friendly character instead of `@`. But it looks cool this way. 😄 
- `<branch1>...<branch2>` - Similar to GitHub's commit range selection functionality you can use this feature to select a range of commits and query just those without querying anything that happened outside of this range.
- `<branch>^` - Queries the base point of the branch, the point when this branch has been created, it is just a sugar for `<branch>@<baseTimestamp>`.

For example to get back how the concept `138875005|SNOMED CT Root Concept|` looked like in the release of `2003-01-31`, execute this request:

```
curl http://localhost:8080/snowowl/snomed-ct/v3/MAIN@<baseTimestamp of branch (or tag) 2003-01-31>/concepts/138875005?expand=descriptions()
```

I hope this clarifies Snow Owl's API and the possibilities. Let me know if you have any further questions.

Cheers,
Mark
