### ISSUE TITLE
'Get Export' not reliable

### ISSUE THREAD

**Issue by psiotwo** [b2ihealthcare/snow-owl#452]
When GETting a previously POSTed export, e.g.

{{SERVER}}/snowowl/snomed-ct/v3/exports/1bbc27b5-a63a-4c27-8f70-c53b837a1045

most of the time the expected response is obtained

`{
    "type": "DELTA",
    "branchPath": "MAIN/TEST",
    "namespaceId": "INT",
    "moduleIds": [
        "10000001000242103"
    ],
    "includeUnpublished": false,
    "codeSystemShortName": "SNOMEDCT",
    "extensionOnly": true,
    "acceptLanguage": "en-US,en-GB",
    "id": "1bbc27b5-a63a-4c27-8f70-c53b837a1045"
}`

But randomly also this response often occurs:

`{
    "status": 404,
    "code": 0,
    "message": "Export run with identifier '1bbc27b5-a63a-4c27-8f70-c53b837a1045' could not be found.",
    "developerMessage": "The requested instance resource (id = '1bbc27b5-a63a-4c27-8f70-c53b837a1045', type = 'Export run') does not exist and/or not yet created.",
    "errorCode": 0,
    "statusCode": 404
}`

Trying the GET request multiple times gets either the first or the second each time.

**Comment by cmark** [comment]
Hi @psiotwo,

Thank you for reporting the issue and sorry for the late reply.
If you have downloaded the RF2 file via the `/:id/archive` endpoint then after another GET request to the export configuration indeed returns an HTTP 404 response. This is by design and how this endpoint is intended to work (mostly because exports in the previous Snow Owl versions could take more than 5 minutes to complete). 
The API is probably going  to be refactored sometime in the near future to a simplified single GET endpoint.
Let me know if you have any further questions.

Cheers,
Mark
