### ISSUE TITLE
Conflicting branches

### ISSUE THREAD

**Issue by joshlk** [b2ihealthcare/snow-owl#461]
Hi,

How do you resolve branch merging conflicts? For example, I am attempting to merge two branches `MAIN/test-1` and `MAIN/test-1/test-2`. I get the following results from `GET /snomed-ct/v3/merges/{id}`:

```
{
  "id": "691edea0-e3af-4d40-9f21-5fc2412ddc1b",
  "source": "MAIN/test-1/test-2",
  "target": "MAIN/test-1",
  "status": "CONFLICTS",
  "scheduledDate": "2019-12-17T13:08:55.618+0000",
  "startDate": "2019-12-17T13:08:55.618+0000",
  "endDate": "2019-12-17T13:08:55.670+0000",
  "conflicts": [
    {
      "componentId": "91000242116",
      "componentType": "description",
      "conflictingAttributes": [
        {
          "property": "term",
          "value": "Special Invitation to participate in clinical trial change 2. test-2",
          "oldValue": "Special Invitation to participate in clinical trial (finding)"
        }
      ],
      "type": "CONFLICTING_CHANGE",
      "message": "description with ID '91000242116' has a conflict of type 'CONFLICTING_CHANGE' on target branch, conflicting attributes are: [term -> old value: Special Invitation to participate in clinical trial (finding), value: Special Invitation to participate in clinical trial change 2. test-2]."
    }
  ]
}
```

What are the next steps I need to do to resolve the conflicts?

**Comment by cmark** [comment]
Hi @joshlk,

Just like in Git, merge conflicts require manual resolution. 
Executing two compares from each branch's perspective (`MAIN` -> `MAIN/a` and `MAIN/a` -> `MAIN`) you can get the changes on each side and using that information you can easily display a user interface similar to GitHub compare view. When there are no conflicts you can proceed to merging of `MAIN/a` into `MAIN`.
When there are conflicts, you need to modify the conflicting attributes/components (usually on the source branch of the merge) in order to resolve the conflict.
In your case, I suggest changing the `term` attribute to the desired value from the two values on the `MAIN/test-1/test-2` branch and try to merge the branch again.

I hope this clarifies how merging and conflict resolution works in Snow Owl. Let me know if you have any further questions.

Cheers,
Mark
There is no automation of any kind of conflicting attributes

**Comment by cmark** [comment]
Let us know if you have any further questions or feel free to open another issue. Closing.
