### ISSUE TITLE
importId not stored in database

### ISSUE THREAD

**Issue by martinmart92** [b2ihealthcare/snow-owl#469]
Hi! 
I have deployed 2 instances of SnowOwl behind a loadbalancer and called the loadbalancer endpoint to import a file.
At the end of the process, it seems like only one of the two instances of SnowOwl knows about the `importId` value: one instance returns a HTTP 404 and the other one returns the expected result:

instance 1:
`{"status":404,"code":0,"message":"SNOMED CT import configuration with identifier 'aeb488d8-b6c5-4354-8306-fe98a4a7ead2' could not be found.","developerMessage":"The requested instance resource (id = 'aeb488d8-b6c5-4354-8306-fe98a4a7ead2', type = 'SNOMED CT import configuration') does not exist and/or not yet created.","errorCode":0,"statusCode":404}`

instance 2:
`{"type":"FULL","branchPath":"MAIN/SNOMEDCT-UK","createVersions":true,"codeSystemShortName":"SNOMEDCT","id":"aeb488d8-b6c5-4354-8306-fe98a4a7ead2","status":"COMPLETED","startDate":"2020-01-17T14:47:58.549+0000","completionDate":"2020-01-17T15:23:24.453+0000"}`

Calling the loadbalancer:
It randomly returns the result above for either instance 1 or for instance 2.
This makes it difficult for a client code to handle real error or adapt to it, and the probability of getting the false-positive 404 increases with the number of instances behind the loadbalancer.

Could storing the import status object in storage (ES) instead of in memory be a possible solution?

**Comment by cmark** [comment]
Hi @martinmart92,

Thank you for reporting. We are aware of this issue.
Yes, the solution would be something like that, store the configuration in ES.
Also, since both the import/export and somewhat long-running operations, it would be beneficial to use the Job API to store and run them along with their configuration values (similar to the current Validation endpoint).

This will be part of an upcoming release (7.4 or 7.5).

Cheers,
Mark

**Comment by martinmart92** [comment]
Ok! thanks for quick answer. I'll close this issue if that's fine with you.
