### ISSUE TITLE
Problem retrieving refsets

### ISSUE THREAD

**Issue by RichardChappell** [b2ihealthcare/snow-owl#482]
I am calling the following endpoints but I am getting confusing results

GET /snomed-ct/v3/{path}/members - Retrieve reference set members from a branch
GET /snomed-ct/v3/{path}/refsets - Retrieve Reference Sets from a branch

Using the Swagger UI, 

http://localhost:8000/snowowl/snomed-ct/v3/MAIN/members returns 50 out of a potential 10067083 records. 

http://localhost:8000/snowowl/snomed-ct/v3/MAIN/refsets?limit=50 returns 0 records.

Why 0 records?  I get the same from my own code so I am wondering if there are any other required parameters. If so, could you give some detail on what they are and what kind of values I should use?

**Comment by cmark** [comment]
Hi @RichardChappell,

This looks like a bug. The endpoint should return reference set documents instead of returning zero. May I ask which version of Snow Owl do you have installed?
The fix will be available soon in the new snow-owl-oss 7.x Docker image and will be released end of next week with the 7.4.0 version.

Cheers,
Mark
