### ISSUE TITLE
Sorting results

### ISSUE THREAD

**Issue by RichardChappell** [b2ihealthcare/snow-owl#512]
I am calling the following

 http://localhost:8000/snowowl/snomed-ct/v3/MAIN/concepts?term=should%20pa&semanticTag=finding&active=true&expand=descriptions()

I am getting this list of concepts (with their descriptions, ignoring inactive)

35737003   - Shoulder-pad sign (finding)
                     Shoulder-pad sign
45326000   - Shoulder region pain
                     Shoulder pain
                     Shoulder pain (finding)
267949000 - Shoulder joint pain
                     Arthralgia of shoulder
                     Shoulder joint pain (finding)
                     Arthralgia of the shoulder region

Now, doing a similar search on the NHS UK SNOMED CT Browser 

https://termbrowser.nhs.uk/?perspective=full&conceptId1=404684003&edition=uk-edition&release=v20191001&server=https://termbrowser.nhs.uk/sct-browser-api/snomed&langRefset=999001261000000100,999000691000001104

I get this list

Shoulder pain                           - Shoulder pain (finding) (45326000)
Shoulder-pad sign                    - Shoulder-pad sign (finding) (35737003)
Shoulder blade pain                 - Scapulalgia (finding) (20793008)
Shoulder joint pain                   - Shoulder joint pain (finding) (267949000)
Shoulder region pain               - Shoulder pain (finding) (45326000)
Shoulder pain (finding)            - Shoulder pain (finding) (45326000)
Shoulder pain from abdomen - Shoulder pain from abdomen (finding) (162039006)
Shoulder-pad sign (finding)    - Shoulder-pad sign (finding) (35737003)

What can I do to get this sort order? The NHS results seem to make more sense.

There is a "sort" parameter, but I only have the Swagger interface to go by and there is no documentation on how to use it.

**Comment by cmark** [comment]
Hi @RichardChappell,

Please apologize for our late reply.

Yes, there are a few key differences between the two searches you have used:

* The Browser is using a length based sorting approach to render shorter terms first.
* The Browser is probably using some degree-of-interest scoring (or we hope it does)
* The Browser is searching descriptions directly via a term filter and showing the concept ID in parenthesis in the result list.
* The Browser is using the `999001261000000100,999000691000001104` language reference sets to extend the range of the search
* The Browser is probably not searching amongst the Text Definitions

The Snow Owl search how ever:
* Using a three layered search algorithm to provide the results:
  * 1. Exact term match
  * 2. All terms match (each of the supplied terms match exactly one word in the given description)
  * 3. All term prefix match (each of the supplied terms match exactly one prefix of any word in the given description)
* The search performs a concept search with a term filter which will eventually turn into the description search you see in the Browser's UI. (this is not an issue, but something worth mentioning)
* No degree-of-interest scoring is applied to the search
* No additional language reference sets are applied to the search
* No description type filter specified to restrict the search to FSNs and Synonyms

To achieve similar result I recommend using the latest Snow Owl 7.5.1 release and the following search parameters:
* `doi=true` - to enable degree-of-interest scoring on the search
* `Accept-Language: en-gb,en-us,en-x-999001261000000100,en-x-999000691000001104` - to search in all INT and UK language reference sets
* `_score:desc` - sorting option to explicitly specify the sorting

```
http://localhost:8000/snowowl/snomed-ct/v3/MAIN/concepts?term=should%20pa&semanticTag=finding&active=true&expand=descriptions()&doi=true&sort=_score:desc
```

_Keep in mind, since the two term scoring methods are different between the two searches, it will be close to impossible to get back the exact same result list as the NHS Browser._ 

Let me know if this helps improving the result list of you search.

Cheers,
Mark
