### ISSUE TITLE
API Doc "try it out" function hangs for API Path- /snomed-ct/v3/{path}/concepts

### ISSUE THREAD

**Issue by colin-e-nhsd** [b2ihealthcare/snow-owl#656]
**SnowOwl**
Version: 7.8.2 (I believe, see earlier feature request)

**Steps to Reproduce**

1. Open a browser window on the server API documentation pages (<host address>/snowowl/)

1. Select the SNOEMED CT API page from the navigation

1. Select the interface to GET Concepts from a branch (/snomed-ct/v3/{path}/concepts)

1. Click the "Try it out" button

The interface will now hang, and then time out with a "This page is not responding" error.

This is reproducible in Firefox 68.11.0ESR and Edge 84.0.522.63 browsers.

**Expected behavior**
The page section for the API should "enable", allowing parameters to be entered and the API tested.

**Version**
 - Snow Owl Version: 7.8.x
 - Elasticsearch Version (external): ?

**Additional context**
Behaviour is the same whether the user is authenticated (via Basic Auth) or not.

**Comment by colin-e-nhsd** [comment]
This was reproducible yesterday in multiple browsers, but not this morning. Closing as it is not reproducible.

**Comment by cmark** [comment]
Hi @colin-e-nhsd,

Thank you for reporting this issue.
Yes, this happens sometimes, because the SNOMED CT model has a recursion in it, and the current Swagger UI version does not support them very well. Opening up multiple endpoints can crash the API docs site and require a full page refresh in order to open the specific endpoint. We are planning to migrate the current version to the new one, to see if that resolves the issue or not, and also move the specification from the current OpenAPI v2 to the v3 format. That might have better support in the latest Swagger UI release than v2.

I'd like to keep this issue open to track the progress of the new Swagger API docs version update.

Cheers,
Mark

**Comment by cmark** [comment]
This issue is currently being investigated and improved on this branch: 
https://github.com/b2ihealthcare/snow-owl/tree/improvement/replace-swagger-ui-rapidoc

Swagger UI is a bit hard to handle and manage at this point and the responsiveness of the interface became unbearable (and non-deterministic) in the past few months, so we are thinking about replacing it with a better alternative that offers a cleaner interface, easier controls, better documentation and most importantly speed.

The planned release version for the new REST API UI is 7.17.0.

**Comment by cmark** [comment]
The fix for this issue has been pushed to the 8.0.0 major release, which is expected around the end of July/early August.

**Comment by cmark** [comment]
Hi @colin-e-nhsd,

The new, improved API documentation site is now available in the latest [8.0.0](https://github.com/b2ihealthcare/snow-owl/releases/tag/v8.0.0) release. Feel free to check it out, if you have the time.

Cheers,
Mark
