### ISSUE TITLE
Publication of Live and Pre-Release content to OntoServer Terminology Server

### ISSUE THREAD

**Issue by colin-e-nhsd** [b2ihealthcare/snow-owl#713]
Our aim is to develop new SNOMED content in volume for Pathology in the UK using a more Agile approach than has been taken in the past. One part of this is to be able to publish pre-release content quickly and easily to users so they can provide feedback before the content is "solidified" in a Live SNOMED release.

Ultimately this could support daily Beta release builds as implemented (I believe) by SNOMED International

We want to be able to publish UK Pathology Module content, whether pre-release or Live versioned material, via the CSIRO OntoServer platform. Having spoken to the CSIRO team about the requirements that platform has for loading RF2, and particularly pre-release content we have identified a number of gaps that will need to be bridged to meet this requirement, direct testing will be required to prove whether this list is complete-

Requirements (general)

1. A Module Dependency Refset (MDR) file that represents the full dependency tree of the selected UK SNOMED Module
1. Availability of the Modules referenced in the MDR, either within the single RF2 export file or accessible separately
1. Valid non-null effectiveTime values in the exported data to allow dependencies to be reconciled during load

Requirements (Pre-Release content)

1. File naming within the RF2 package, as specified in the SI documentation, that uses the "x" prefix to denote non-Live content
1. Full timestamps (i.e date+time) in effectiveTime values of pre-release modules (note, the OntoServer platform does not strictly demand this, but we understand this is the SI specified format for pre-release data)
1. Content loaded with a version URI rooted at http://snomed.info/xsct (vs http://snomed.info/sct for Live content)

**Options**
There are two options for exporting prerelease content we are aware of (there may be others).

1. We can export RF2 from a task branch in SnowOwl. This gives us-
- Blank/null effectiveTime values
- Empty (header only) MDR file
- Does not follow pre-release file naming patterns within the RF2 export

1. In theory we could implement an approach where we "rewind time" by-
- Creating a snapshot of the SnowOwl server instance just before versioning
- Versioning the content 
- Generating a release

then-
- Reverting the snapshot to put the SnowOwl instance back in the state before the versioning step
- Continuing to edit content in the task branch

This gives us (we believe)-
- Valid dates in the effectiveTime values, (but not datetime format)
- An MDR file based on SnowOwl's notion of the module dependencies, which does not represent the full structure of the UK modules
- Does not follow pre-release file naming patterns within the RF2 export

By comparison we believe publishing Live content to OntoServer should be more straightforward, but the issue with the MDR remains.

None of these options represent a smooth direct path to publishing content. In particular the format of exported PreRelease content is quite a long way from the required structure.

I would like B2i's comments on these requirements please. What might be on the roadmap already, and what is not. The technical feasibility of possible solutions, and any issues with the requirements overall would also be of interest.

**Comment by cmark** [comment]
Hi @colin-e-nhsd,

Thank you for raising your issue here on GitHub.

I'm going to answer most of the questions here on our public channel related to the open-source parts of our terminology server, but for further discussions of this matter, I recommend contacting us via our [support channel](mailto:support@b2i.sg).

Requirements:
> A Module Dependency Refset (MDR) file that represents the full dependency tree of the selected UK SNOMED Module

This file is already being generated by Snow Owl's RF2 export in all cases. How ever, to produce valid content, Snow Owl requires a version for the unpublished changes, otherwise it cannot compute the correct module dependency changes. This is because components will get their `effectiveTime` values during versioning, thus module dependency members can be generated automatically based on those changes. In order to support this requirement the exporter could be improved in a way to produce the MDR entries if the export is requested with a `transientEffectiveTime` (see Valid non-null `effectiveTime` values part below).

> Availability of the Modules referenced in the MDR, either within the single RF2 export file or accessible separately

Snow Owl maintains a strict consistency when referencing IDs and content. For example: exporting just the UK PA from a Snow Owl server will maintain consistency and return the components that belong to that module.

> Valid non-null effectiveTime values in the exported data to allow dependencies to be reconciled during load

In certain use cases, unpublished SNOMED CT changes need to be migrated to other Snow Owl servers, thus Snow Owl's RF2 export always exports the actual `effectiveTime` values registered for the components, be it `null` (which results in an empty `effectiveTime` value) or an exact value. However, to support daily build scenarios where the target system does not support `null/empty` values in the `effectiveTime` column, Snow Owl is able to generate a transient `effectiveTime` value for those rows in the resulting RF2 export file. By specifying a valid `yyyyMMdd` effective time value in the `transientEffectiveTime` argument, Snow Owl will change the unpublished components to use that value instead of `null/empty`. 

> File naming within the RF2 package, as specified in the SI documentation, that uses the "x" prefix to denote non-Live content

Yes, this is currently unsupported and it could be tied to the `transientEffectiveTime` configuration setting to produce the `x` prefixed files if there are unpublished components.

> Full timestamps (i.e date+time) in effectiveTime values of pre-release modules (note, the OntoServer platform does not strictly demand this, but we understand this is the SI specified format for pre-release data)

According to the official SNOMED TIG, effectiveTime values never have time parts, only the date part is registered.

From https://confluence.ihtsdotools.org/display/DOCRELFMT/4.2.1+Concept+File+Specification:
_Note: In distribution files the effectiveTime should follow the short ISO date format (YYYYMMDD) and should not include the hours, minutes, seconds or timezone indicator._

If there is an official document or statement that describes this as a feature supported by the RF2 specification, then please don't hesitate to share it with us.

> Content loaded with a version URI rooted at http://snomed.info/xsct (vs http://snomed.info/sct for Live content)

Not sure if this is relevant for Snow Owl, but for any FHIR server it might be since those need to register the pre-release content with this URI. I also suggest putting the module part in it, so it will represent the actual module as well, not just the SNOMED CT terminology.

> We can export RF2 from a task branch in SnowOwl. This gives us-
> Blank/null effectiveTime values
> Empty (header only) MDR file
> Does not follow pre-release file naming patterns within the RF2 export

This is the way it should behave I think. The two missing features at the moment are the MDR generation for unpublished content and the pre-release file naming patterns.

> In theory we could implement an approach where we "rewind time"

While this could work, I suggest not taking this into consideration at all. With the `transientEffectiveTime` RF2 export feature you can simulate the versioning without making the content in Snow Owl versioned at all, and that should be enough to get you started.

Let us know if you have any questions issues regarding the points I have responded to here on GitHub.
For any other questions/issues you may have, I'm looking forward to a support ticket raised in our support channel.

Regards,
Mark

**Comment by colin-e-nhsd** [comment]
Hi Mark, thanks for the response. Happy to continue the conversation on the details through the support channel. One item is worth discussing here though. On-

>> According to the official SNOMED TIG, effectiveTime values never have time parts, only the date part is registered.

The reference provided by the OntoServer team for this is https://confluence.ihtsdotools.org/x/9Ia2AQ although I can see this just describes the **_Time_** (full timestamp) data type, not it's intended uses.

The table definitions for importing RF2 clearly define EffectiveTime as a DATETIME, but also state the actual values are most commonly just dates. It would take more digging in the SNOMED specification to find if it does describe when/if date+time vs, simple date values should be used in versioning.

Rationally, I can see a case for using date+time timestamps in prerelease content.

- Firstly because the values are likely to be unique even in a test environment where you might be running multiple attempts at a release through a pipeline of tools in quick succession, whereas multiple runs with one date applied could trip over each other.

- Secondly because SNOMED has overloaded the idea of a release version name (tag) and a release date onto a single value, that carries the implication that putting a date on content is synonymous with "releasing" it as a formal (Live) data set. If data is NOT formally Live, the obvious effectiveTime value to apply is null, but if that doesn't work because it confuses the loading routines of client systems, the next best solution, rather than asking the author to invent guaranteed-unique dates as versions, is to use the result of a call to now().  Inserting it as a date+time makes it easy for clients to differentiate prerelease effectiveTimes from those for released data.

Having said all this, I think the OntoServer application doesn't actually enforce the date+time requirement, it's just a recommendation. However they cannot currently handle null effectiveTime values, although is it up for consideration whether it might be possible, e.g. by inferring a value of now() for effectiveTime fields that are blank on load.

**Comment by cmark** [comment]
Hi @colin-e-nhsd,

Yes, we couldn't find that information in the official docs either, only the page you have referenced that describes the Time Data type, which indeed supports times, not just the date, but there were no actual use cases for it.
These might be the first real-world use cases that require date+time in `effectiveTime` values, thank you for sharing them.
Snow Owl has the ability to represent date+time in `effectiveTime` values on component data, but there could be places where this is clearly not supported. One that I can think of is the import-export process, we probably only support the `yyyyMMdd` format at the moment.

> However they cannot currently handle null effectiveTime values, although is it up for consideration whether it might be possible, e.g. by inferring a value of now() for effectiveTime fields that are blank on load.

While we work out the details of supporting this (and MDR + file-naming changes), the only option to extract unpublished data with actual effectiveTime values is to use the `transientEffectiveTime` export argument. 
Could you please give that a go and let us know if that supports your initial daily build needs?

Cheers,
Mark

**Comment by cmark** [comment]
Hi @colin-e-nhsd,

I consider this part of the ticket closed. If you need any further feedback on this feel free to contact us via our support channels.

Regards,
Mark
